import re
import json
from typing import Any, Dict


def relocate_imports_inside_function(code: str) -> str:
    """Move imports inside function to avoid global namespace issues."""
    lines = code.split('\n')
    imports = []
    function_body = []
    inside_function = False
    function_indent = 0
    
    for line in lines:
        stripped = line.strip()
        
        # Detect function definition
        if stripped.startswith('def ') and ':' in stripped:
            inside_function = True
            function_indent = len(line) - len(line.lstrip())
            function_body.append(line)
            continue
        
        if inside_function:
            # Check if we're still in the function
            current_indent = len(line) - len(line.lstrip())
            if line.strip() and current_indent <= function_indent and not stripped.startswith('#'):
                # End of function
                inside_function = False
            
            # Collect imports inside function
            if inside_function and (stripped.startswith('import ') or stripped.startswith('from ')):
                imports.append(stripped)
            else:
                function_body.append(line)
        else:
            # Collect imports outside function
            if stripped.startswith('import ') or stripped.startswith('from '):
                imports.append(stripped)
            else:
                function_body.append(line)
    
    # Rebuild code with imports at the beginning of function
    if imports:
        # Find the function definition and add imports after it
        result_lines = []
        for i, line in enumerate(function_body):
            result_lines.append(line)
            if 'def ' in line and ':' in line:
                # Add imports after function definition
                next_indent = len(line) - len(line.lstrip()) + 4
                for imp in imports:
                    result_lines.append(' ' * next_indent + imp)
                break
        
        # Add the rest of the function body
        result_lines.extend(function_body[i+1:])
        return '\n'.join(result_lines)
    
    return code


def add_comments_to_top(code: str, agent_name: str) -> str:
    """Add agent name and timestamp comments to code."""
    import datetime
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    comment = f"""
# Generated by {agent_name}
# Timestamp: {timestamp}
# AI Data Science Team

"""
    return comment + code


def format_agent_name(agent_name: str) -> str:
    """Format agent name for display."""
    return f"[{agent_name.upper()}]"


def format_recommended_steps(steps: str, heading: str = "# Recommended Steps:") -> str:
    """Format recommended steps with heading."""
    return f"{heading}\n\n{steps}"


def get_generic_summary(data: Dict[str, Any]) -> str:
    """Generate a generic summary from data."""
    if not data:
        return "No data available."
    
    summary_lines = ["## Summary"]
    
    for key, value in data.items():
        if isinstance(value, dict):
            summary_lines.append(f"### {key.title()}")
            for sub_key, sub_value in value.items():
                summary_lines.append(f"- {sub_key}: {sub_value}")
        else:
            summary_lines.append(f"- {key}: {value}")
    
    return '\n'.join(summary_lines)


def remove_consecutive_duplicates(items: list) -> list:
    """Remove consecutive duplicates from list."""
    if not items:
        return []
    
    result = [items[0]]
    for item in items[1:]:
        if item != result[-1]:
            result.append(item)
    
    return result


def clean_code_output(code: str) -> str:
    """Clean code output by removing extra whitespace and formatting."""
    # Remove multiple consecutive newlines
    code = re.sub(r'\n\s*\n\s*\n', '\n\n', code)
    
    # Remove trailing whitespace
    code = '\n'.join(line.rstrip() for line in code.split('\n'))
    
    return code.strip()
